#ifndef VERTICA_UDFS_THETA_CONST_H
#define VERTICA_UDFS_THETA_CONST_H

#define DATASKETCHES_LOG_NOMINAL_VALUE_PARAMETER_NAME "logK"
#define DATASKETCHES_LOG_NOMINAL_VALUE_DEFAULT 12
#define DATASKETCHES_LOG_NOMINAL_VALUE_MIN 5
// Vertica supports maximum 65000 bytes in a binary field, hence the limit.
#define DATASKETCHES_LOG_NOMINAL_VALUE_MAX 12
#define DATASKETCHES_SEED_PARAMETER_NAME "seed"
#define DATASKETCHES_SEED_DEFAULT 9001


#endif //VERTICA_UDFS_THETA_CONST_H
